- name: Run SonarQube Scan
  uses: SonarSource/sonarqube-scan-action@v5
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  with:
    args: >
      -Dsonar.organization=hieu-coder-svg
      -Dsonar.projectKey=Hieu-coder-svg_ass
